# Generated by Django 5.1.15 on 2026-10-08 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name_en",
                    models.CharField(max_length=150, verbose_name="name (English)"),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=150, verbose_name="name (Arabic)"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=30, verbose_name="phone"),
                ),
                (
                    "address_en",
                    models.TextField(blank=True, verbose_name="address (English)"),
                ),
                (
                    "address_ar",
                    models.TextField(blank=True, verbose_name="address (Arabic)"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.clinic",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "branch",
                "verbose_name_plural": "branches",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ProcedureCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name_en",
                    models.CharField(max_length=100, verbose_name="name (English)"),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=100, verbose_name="name (Arabic)"),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="order"),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.clinic",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "procedure category",
                "verbose_name_plural": "procedure categories",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name_en",
                    models.CharField(max_length=100, verbose_name="name (English)"),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=100, verbose_name="name (Arabic)"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rooms",
                        to="masterdata.branch",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.clinic",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "room",
                "verbose_name_plural": "rooms",
                "ordering": ["branch_id", "id"],
            },
        ),
        migrations.CreateModel(
            name="Chair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name_en",
                    models.CharField(max_length=100, verbose_name="name (English)"),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=100, verbose_name="name (Arabic)"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="order"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chairs",
                        to="masterdata.branch",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.clinic",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chairs",
                        to="masterdata.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "chair",
                "verbose_name_plural": "chairs",
                "ordering": ["branch_id", "sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="StaffMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name_en",
                    models.CharField(max_length=150, verbose_name="name (English)"),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=150, verbose_name="name (Arabic)"),
                ),
                (
                    "staff_type",
                    models.CharField(
                        choices=[
                            ("dentist", "Dentist"),
                            ("assistant", "Dental assistant"),
                            ("technician", "Lab technician"),
                            ("reception", "Receptionist"),
                            ("accountant", "Accountant"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=30, verbose_name="phone"),
                ),
                (
                    "commission_type",
                    models.CharField(
                        choices=[
                            ("none", "No commission"),
                            ("percent_collected", "Percent of amount collected"),
                            ("percent_billed", "Percent of amount billed"),
                            ("fixed_per_procedure", "Fixed amount per procedure"),
                        ],
                        default="none",
                        max_length=30,
                        verbose_name="commission rule",
                    ),
                ),
                (
                    "commission_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="commission value",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, max_length=7, verbose_name="calendar color"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "branches",
                    models.ManyToManyField(
                        blank=True,
                        related_name="staff",
                        to="masterdata.branch",
                        verbose_name="branches",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.clinic",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "staff member",
                "verbose_name_plural": "staff",
                "ordering": ["name_en"],
            },
        ),
        migrations.CreateModel(
            name="Procedure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=20, verbose_name="code")),
                (
                    "name_en",
                    models.CharField(max_length=200, verbose_name="name (English)"),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=200, verbose_name="name (Arabic)"),
                ),
                (
                    "default_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="default price",
                    ),
                ),
                (
                    "default_duration_minutes",
                    models.PositiveSmallIntegerField(
                        default=30, verbose_name="default duration (minutes)"
                    ),
                ),
                (
                    "needs_lab",
                    models.BooleanField(default=False, verbose_name="needs lab work"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.clinic",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procedures",
                        to="masterdata.procedurecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "procedure",
                "verbose_name_plural": "procedure catalog",
                "ordering": ["category__sort_order", "code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("clinic", "code"),
                        name="unique_procedure_code_per_clinic",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkingHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        verbose_name="day",
                    ),
                ),
                (
                    "is_closed",
                    models.BooleanField(default=False, verbose_name="closed"),
                ),
                (
                    "opens_at",
                    models.TimeField(blank=True, null=True, verbose_name="opens at"),
                ),
                (
                    "closes_at",
                    models.TimeField(blank=True, null=True, verbose_name="closes at"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="working_hours",
                        to="masterdata.branch",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.clinic",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "working hours",
                "verbose_name_plural": "working hours",
                "ordering": ["branch_id", "weekday"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("branch", "weekday"), name="unique_hours_per_branch_day"
                    )
                ],
            },
        ),
    ]
