# Generated by Django 5.1.15 on 2026-10-08 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("masterdata", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file_number",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="file number"
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="name (Arabic)"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="name (English)"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("female", "Female"), ("male", "Male")],
                        max_length=10,
                        verbose_name="gender",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="date of birth"
                    ),
                ),
                ("phone", models.CharField(max_length=30, verbose_name="mobile")),
                (
                    "phone_alt",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="other phone"
                    ),
                ),
                (
                    "whatsapp_opt_in",
                    models.BooleanField(
                        default=True, verbose_name="WhatsApp messages allowed"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("ar", "Arabic")],
                        default="ar",
                        max_length=2,
                        verbose_name="language",
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="national ID"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="address")),
                (
                    "occupation",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="occupation"
                    ),
                ),
                (
                    "referral_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("walk_in", "Walk-in"),
                            ("friend", "Friend or family"),
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("google", "Google"),
                            ("doctor", "Referred by a doctor"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="how they heard of us",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="front-desk notes"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("search_text", models.TextField(default="", editable=False)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.clinic",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "home_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="masterdata.branch",
                        verbose_name="branch",
                    ),
                ),
                (
                    "preferred_dentist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="masterdata.staffmember",
                        verbose_name="dentist",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "patient",
                "verbose_name_plural": "patients",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MedicalHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "diabetes",
                    models.BooleanField(default=False, verbose_name="diabetes"),
                ),
                (
                    "hypertension",
                    models.BooleanField(
                        default=False, verbose_name="high blood pressure"
                    ),
                ),
                (
                    "heart_disease",
                    models.BooleanField(default=False, verbose_name="heart disease"),
                ),
                (
                    "bleeding_disorder",
                    models.BooleanField(
                        default=False, verbose_name="bleeding disorder"
                    ),
                ),
                (
                    "blood_thinners",
                    models.BooleanField(
                        default=False, verbose_name="takes blood thinners"
                    ),
                ),
                ("asthma", models.BooleanField(default=False, verbose_name="asthma")),
                (
                    "epilepsy",
                    models.BooleanField(default=False, verbose_name="epilepsy"),
                ),
                (
                    "hepatitis",
                    models.BooleanField(default=False, verbose_name="hepatitis"),
                ),
                (
                    "kidney_disease",
                    models.BooleanField(default=False, verbose_name="kidney disease"),
                ),
                (
                    "pregnant",
                    models.BooleanField(default=False, verbose_name="pregnant"),
                ),
                ("smoker", models.BooleanField(default=False, verbose_name="smoker")),
                ("allergies", models.TextField(blank=True, verbose_name="allergies")),
                (
                    "medications",
                    models.TextField(blank=True, verbose_name="current medications"),
                ),
                (
                    "past_surgeries",
                    models.TextField(blank=True, verbose_name="past operations"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="other notes")),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.clinic",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_history",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "medical history",
                "verbose_name_plural": "medical histories",
            },
        ),
        migrations.CreateModel(
            name="MedicalAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("allergy", "Allergy"),
                            ("condition", "Condition"),
                            ("medication", "Medication"),
                            ("other", "Other"),
                        ],
                        default="condition",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                ("text", models.CharField(max_length=200, verbose_name="alert")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.clinic",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "medical alert",
                "verbose_name_plural": "medical alerts",
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["clinic", "phone"], name="patients_pa_clinic__c795cb_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="patient",
            constraint=models.UniqueConstraint(
                fields=("clinic", "file_number"), name="unique_file_number_per_clinic"
            ),
        ),
    ]
