# Generated by Django 5.1.15 on 2026-10-09 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0002_initial"),
        ("clinical", "0001_initial"),
        ("core", "0001_initial"),
        ("masterdata", "0001_initial"),
        ("patients", "0002_medicalalert_guidance_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last", models.PositiveIntegerField(default=0)),
                (
                    "clinic",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.clinic",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LabCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "number",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="number"
                    ),
                ),
                (
                    "restoration",
                    models.CharField(
                        choices=[
                            ("crown", "Crown"),
                            ("bridge", "Bridge"),
                            ("veneer", "Veneer"),
                            ("inlay_onlay", "Inlay or onlay"),
                            ("implant_crown", "Implant crown"),
                            ("post_core", "Post and core"),
                            ("denture_full", "Full denture"),
                            ("denture_partial", "Partial denture"),
                            ("night_guard", "Night guard"),
                            ("temporary", "Temporary"),
                            ("other", "Other"),
                        ],
                        default="crown",
                        max_length=20,
                        verbose_name="restoration",
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        choices=[
                            ("zirconia", "Zirconia"),
                            ("emax", "Lithium disilicate (e.max)"),
                            ("pfm", "Porcelain fused to metal"),
                            ("metal", "Metal"),
                            ("pmma", "PMMA"),
                            ("composite", "Composite"),
                            ("acrylic", "Acrylic"),
                            ("other", "Other"),
                        ],
                        default="zirconia",
                        max_length=20,
                        verbose_name="material",
                    ),
                ),
                (
                    "shade",
                    models.CharField(blank=True, max_length=20, verbose_name="shade"),
                ),
                (
                    "teeth",
                    models.CharField(blank=True, max_length=60, verbose_name="teeth"),
                ),
                (
                    "units",
                    models.PositiveSmallIntegerField(default=1, verbose_name="units"),
                ),
                (
                    "instructions",
                    models.TextField(blank=True, verbose_name="instructions"),
                ),
                ("due_date", models.DateField(verbose_name="due date")),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("received", "Scan received"),
                            ("design", "CAD design"),
                            ("milling", "Milling"),
                            ("finishing", "Sintering and glaze"),
                            ("ready", "Ready for try-in"),
                            ("delivered", "Delivered"),
                        ],
                        default="received",
                        max_length=20,
                        verbose_name="stage",
                    ),
                ),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancel_reason",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="cancellation reason"
                    ),
                ),
                (
                    "remake_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fit", "Poor fit"),
                            ("shade", "Wrong shade"),
                            ("fracture", "Fracture"),
                            ("design", "Design or contacts"),
                            ("patient", "Patient request"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="remake reason",
                    ),
                ),
                (
                    "remake_note",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="remake note"
                    ),
                ),
                (
                    "remake_charged_to",
                    models.CharField(
                        blank=True,
                        choices=[("lab", "Lab"), ("clinic", "Clinic")],
                        max_length=10,
                        verbose_name="remake cost carried by",
                    ),
                ),
                (
                    "material_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="material cost",
                    ),
                ),
                (
                    "labour_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="labour cost",
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_cases",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.clinic",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dentist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordered_lab_cases",
                        to="masterdata.staffmember",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lab_cases",
                        to="patients.patient",
                    ),
                ),
                (
                    "plan_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lab_cases",
                        to="clinical.treatmentplanline",
                    ),
                ),
                (
                    "remake_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="remakes",
                        to="lab.labcase",
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lab_cases",
                        to="masterdata.staffmember",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "lab case",
                "verbose_name_plural": "lab cases",
                "ordering": ["due_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="StageEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("received", "Scan received"),
                            ("design", "CAD design"),
                            ("milling", "Milling"),
                            ("finishing", "Sintering and glaze"),
                            ("ready", "Ready for try-in"),
                            ("delivered", "Delivered"),
                        ],
                        max_length=20,
                        verbose_name="stage",
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, verbose_name="note"),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="lab.labcase",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.clinic",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "lab stage",
                "verbose_name_plural": "lab stages",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="labcase",
            constraint=models.UniqueConstraint(
                fields=("clinic", "number"), name="unique_lab_case_number"
            ),
        ),
    ]
