# Generated by Django 5.1.15 on 2026-10-09 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0001_initial"),
        ("lab", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="labcase",
            name="abutment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("stock", "Stock abutment"),
                    ("custom_ti", "Custom titanium"),
                    ("zirconia", "Zirconia"),
                    ("ti_base", "Ti-base hybrid"),
                ],
                max_length=20,
                verbose_name="abutment",
            ),
        ),
        migrations.AddField(
            model_name="labcase",
            name="cervical_shade",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="cervical shade"
            ),
        ),
        migrations.AddField(
            model_name="labcase",
            name="contacts",
            field=models.CharField(
                blank=True,
                choices=[("light", "Light"), ("normal", "Normal"), ("tight", "Tight")],
                max_length=10,
                verbose_name="contacts",
            ),
        ),
        migrations.AddField(
            model_name="labcase",
            name="enclosures",
            field=models.JSONField(
                blank=True, default=list, verbose_name="received with the order"
            ),
        ),
        migrations.AddField(
            model_name="labcase",
            name="hold_reason",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="hold reason"
            ),
        ),
        migrations.AddField(
            model_name="labcase",
            name="implant_platform",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="implant platform"
            ),
        ),
        migrations.AddField(
            model_name="labcase",
            name="implant_system",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="implant system"
            ),
        ),
        migrations.AddField(
            model_name="labcase",
            name="incisal_shade",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="incisal shade"
            ),
        ),
        migrations.AddField(
            model_name="labcase",
            name="margin",
            field=models.CharField(
                blank=True,
                choices=[
                    ("chamfer", "Chamfer"),
                    ("shoulder", "Shoulder"),
                    ("knife_edge", "Knife edge"),
                    ("porcelain_butt", "Porcelain butt margin"),
                    ("metal_collar", "Metal collar"),
                ],
                max_length=20,
                verbose_name="margin",
            ),
        ),
        migrations.AddField(
            model_name="labcase",
            name="occlusion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("in", "In occlusion"),
                    ("light", "Light occlusion"),
                    ("out", "Out of occlusion"),
                ],
                max_length=10,
                verbose_name="occlusion",
            ),
        ),
        migrations.AddField(
            model_name="labcase",
            name="on_hold",
            field=models.BooleanField(default=False, verbose_name="on hold"),
        ),
        migrations.AddField(
            model_name="labcase",
            name="outsource_tracking",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="outside lab reference"
            ),
        ),
        migrations.AddField(
            model_name="labcase",
            name="outsourced_to",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="sent to outside lab"
            ),
        ),
        migrations.AddField(
            model_name="labcase",
            name="pan_number",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="pan number"
            ),
        ),
        migrations.AddField(
            model_name="labcase",
            name="pontic",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ridge_lap", "Ridge lap"),
                    ("modified_ridge_lap", "Modified ridge lap"),
                    ("ovate", "Ovate"),
                    ("sanitary", "Sanitary (hygienic)"),
                ],
                max_length=20,
                verbose_name="pontic design",
            ),
        ),
        migrations.AddField(
            model_name="labcase",
            name="priority",
            field=models.CharField(
                choices=[("normal", "Normal"), ("rush", "Rush")],
                default="normal",
                max_length=10,
                verbose_name="priority",
            ),
        ),
        migrations.AddField(
            model_name="labcase",
            name="retention",
            field=models.CharField(
                blank=True,
                choices=[("screw", "Screw retained"), ("cement", "Cement retained")],
                max_length=10,
                verbose_name="retention",
            ),
        ),
        migrations.AddField(
            model_name="labcase",
            name="shade_guide",
            field=models.CharField(
                choices=[
                    ("vita_classic", "VITA Classical"),
                    ("vita_3d", "VITA 3D-Master"),
                    ("other", "Other"),
                ],
                default="vita_classic",
                max_length=20,
                verbose_name="shade guide",
            ),
        ),
        migrations.AddField(
            model_name="labcase",
            name="stump_shade",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="stump shade"
            ),
        ),
        migrations.AlterField(
            model_name="labcase",
            name="plan_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lab_cases",
                to="clinical.treatmentplanline",
            ),
        ),
        migrations.AlterField(
            model_name="labcase",
            name="stage",
            field=models.CharField(
                choices=[
                    ("received", "Scan received"),
                    ("design", "CAD design"),
                    ("milling", "Milling and printing"),
                    ("finishing", "Sintering and glaze"),
                    ("qc", "Quality check"),
                    ("ready", "Ready for try-in"),
                    ("delivered", "Delivered"),
                ],
                default="received",
                max_length=20,
                verbose_name="stage",
            ),
        ),
        migrations.AlterField(
            model_name="stageevent",
            name="stage",
            field=models.CharField(
                choices=[
                    ("received", "Scan received"),
                    ("design", "CAD design"),
                    ("milling", "Milling and printing"),
                    ("finishing", "Sintering and glaze"),
                    ("qc", "Quality check"),
                    ("ready", "Ready for try-in"),
                    ("delivered", "Delivered"),
                ],
                max_length=20,
                verbose_name="stage",
            ),
        ),
    ]
